export const TEST_PLANNER = {
  source: "Test Planner Yakeen NEET 3.0 2027",
  sourcePages: 10,
  subjects: ["Physics", "Chemistry", "Botany", "Zoology"],
  tests: [
    {number:1,title:"NEET-1",date:"2026-09-13",type:"Part Test",syllabus:{Physics:["Basic Maths & Calculus (Mathematical Tools)"],Chemistry:["Some Basic Concept of Chemistry"],Botany:["Cell - The Unit of Life"],Zoology:["Structural Organization in Animals"]}},
    {number:2,title:"NEET-2",date:"2026-10-04",type:"Part Test",syllabus:{Physics:["Units and Measurements","Vectors"],Chemistry:["Redox Reaction"],Botany:["Cell Cycle and Cell Division","The Living World"],Zoology:["Breathing and Exchange of Gases"]}},
    {number:3,title:"Rank Booster Test-1",date:"2026-10-25",type:"Part Test / Rank Booster",syllabus:{Physics:["Basic Maths & Calculus (Mathematical Tools)","Units and Measurements","Vectors"],Chemistry:["Some Basic Concept of Chemistry","Redox Reaction"],Botany:["Cell - The Unit of Life","Cell Cycle and Cell Division","The Living World"],Zoology:["Structural Organization in Animals","Breathing and Exchange of Gases"]}},
    {number:4,title:"NEET-3",date:"2026-11-22",type:"Part Test",syllabus:{Physics:["Motion in a straight line","Motion in a plane","Laws of motion","Work, energy and power"],Chemistry:["Solutions","Thermodynamics","Equilibrium","Electrochemistry"],Botany:["Biological Classification","Plant Kingdom"],Zoology:["Body Fluids and Circulation","Excretory Products & their Elimination"]}},
    {number:5,title:"NEET-4",date:"2026-12-06",type:"Part Test",syllabus:{Physics:["Centre of mass and System of Particles","Rotational Motion","Gravitation","Mechanical Properties of Solids"],Chemistry:["Structure of Atom","Chemical Kinetics","Classification of Elements and Periodicity in Properties"],Botany:["Morphology of Flowering Plants","Anatomy of Flowering Plants"],Zoology:["Locomotion & Movement","Neural Control & Coordination"]}},
    {number:6,title:"Rank Booster Test-2",date:"2026-12-20",type:"Part Test / Rank Booster",syllabus:{Physics:["Basic Maths & Calculus (Mathematical Tools)","Units and Measurements","Vectors","Motion in a straight line","Motion in a plane","Laws of motion","Work, energy and power","Centre of mass and System of Particles","Rotational Motion","Gravitation","Mechanical Properties of Solids"],Chemistry:["Some Basic Concept of Chemistry","Redox Reaction","Solutions","Thermodynamics","Equilibrium","Electrochemistry","Structure of Atom","Chemical Kinetics","Classification of Elements and Periodicity in Properties"],Botany:["Cell - The Unit of Life","Cell Cycle and Cell Division","The Living World","Biological Classification","Plant Kingdom","Morphology of Flowering Plants","Anatomy of Flowering Plants"],Zoology:["Structural Organization in Animals","Breathing and Exchange of Gases","Body Fluids and Circulation","Excretory Products & their Elimination","Locomotion & Movement","Neural Control & Coordination"]}},
    {number:7,title:"NEET-5",date:"2027-01-03",type:"Part Test",syllabus:{Physics:["Mechanical Properties of Fluids","Thermal Properties of matter","Kinetic Theory","Thermodynamics","Oscillations"],Chemistry:["Chemical Bonding and Molecular Structure","Organic Chemistry: Some Basic Principles and Techniques (IUPAC Naming)"],Botany:["Respiration in Plants","Photosynthesis in Higher Plants"],Zoology:["Chemical Coordination & Integration","Animal Kingdom"]}},
    {number:8,title:"NEET-6",date:"2027-01-17",type:"Part Test",syllabus:{Physics:["Waves","Electric Charges and Fields"],Chemistry:["Organic Chemistry: Some Basic Principles and Techniques (Isomerism)"],Botany:["Plant Growth and Development"],Zoology:["Biomolecules"]}},
    {number:9,title:"Rank Booster Test-3",date:"2027-01-31",type:"Part Test / Rank Booster",syllabus:{Physics:["Basic Maths & Calculus (Mathematical Tools)","Units and Measurements","Vectors","Motion in a straight line","Motion in a plane","Laws of motion","Work, energy and power","Centre of mass and System of Particles","Rotational Motion","Gravitation","Mechanical Properties of Solids","Mechanical Properties of Fluids","Thermal Properties of matter","Kinetic Theory","Thermodynamics","Oscillations","Waves","Electric Charges and Fields"],Chemistry:["Some Basic Concept of Chemistry","Redox Reaction","Solutions","Thermodynamics","Equilibrium","Electrochemistry","Structure of Atom","Chemical Kinetics","Classification of Elements and Periodicity in Properties","Chemical Bonding and Molecular Structure","Organic Chemistry: Some Basic Principles and Techniques (IUPAC Naming)","Organic Chemistry: Some Basic Principles and Techniques (Isomerism)"],Botany:["Cell - The Unit of Life","Cell Cycle and Cell Division","The Living World","Biological Classification","Plant Kingdom","Morphology of Flowering Plants","Anatomy of Flowering Plants","Respiration in Plants","Photosynthesis in Higher Plants","Plant Growth and Development"],Zoology:["Structural Organization in Animals","Breathing and Exchange of Gases","Body Fluids and Circulation","Excretory Products & their Elimination","Locomotion & Movement","Neural Control & Coordination","Chemical Coordination & Integration","Animal Kingdom","Biomolecules"]}},
    {number:10,title:"NEET-7",date:"2027-02-14",type:"Part Test",syllabus:{Physics:["Electrostatic Potential","Current Electricity","Capacitance","Moving Charges and Magnetism"],Chemistry:["Organic Chemistry: Some Basic Principles and Techniques (GOC)"],Botany:["Sexual Reproduction in Flowering Plant"],Zoology:["Human Reproduction","Reproductive Health"]}},
    {number:11,title:"NEET-8",date:"2027-02-28",type:"Part Test",syllabus:{Physics:["Magnetism and Matter","Electromagnetic Induction","Alternating Current","Electromagnetic Waves"],Chemistry:["Hydrocarbon","Haloalkanes and Haloarenes","Alcohols, Ethers and Phenols"],Botany:["Molecular Basis of Inheritance"],Zoology:["Human Health and Diseases"]}},
    {number:12,title:"AITS-6",date:"2027-03-14",type:"Part Test",syllabus:{Physics:["Electrostatic Potential and Capacitance","Current Electricity"],Chemistry:["Organic Chemistry - General Organic Chemistry","Hydrocarbon","Haloalkanes and Haloarenes"],Botany:["Molecular Basis of Inheritance"],Zoology:["Reproductive Health","Biomolecules"]}},
    {number:13,title:"AITS-7",date:"2027-03-21",type:"Part Test",syllabus:{Physics:["Moving Charges and Magnetism","Magnetism and Matter","Electromagnetic Induction"],Chemistry:["Alcohols, Phenols and Ethers","Aldehydes, Ketones and Carboxylic Acids","Amines","Bio-molecules"],Botany:["Principles of Inheritance and Variation"],Zoology:["Human Health and Disease"]}},
    {number:14,title:"NEET-9",date:"2027-03-24",type:"Full Test",syllabus:{Physics:["Full Syllabus"],Chemistry:["Full Syllabus"],Botany:["Full Syllabus"],Zoology:["Full Syllabus"]}},
    {number:15,title:"AITS-8",date:"2027-03-28",type:"Part Test",syllabus:{Physics:["Alternating Current","Electromagnetic Waves","Ray Optics and Optical Instruments","Wave Optics"],Chemistry:["Purification and Analysis of Organic Compound","Classification of Elements and Periodicity in Properties","Chemical Bonding and Molecular Structure"],Botany:["Respiration in Plants","Photosynthesis in Higher Plants","Plant Growth and Development"],Zoology:["Evolution"]}},
    {number:16,title:"NEET-10",date:"2027-03-31",type:"Full Test",syllabus:{Physics:["Full Syllabus"],Chemistry:["Full Syllabus"],Botany:["Full Syllabus"],Zoology:["Full Syllabus"]}},
    {number:17,title:"AITS-9",date:"2027-04-04",type:"Full Test",syllabus:{Physics:["Dual Nature of Radiation and Matter","Atoms","Nuclei","Semiconductor Electronics - Materials, Devices and Simple Circuits"],Chemistry:["Coordination Compounds","The p-Block Elements","The d- and f- block Elements","Salt Analysis"],Botany:["Organisms and Population","Ecosystem","Biodiversity and Conservation"],Zoology:["Biotechnology - Principles and Processes","Biotechnology and its Applications"]}},
    {number:18,title:"AITS-10",date:"2027-04-11",type:"Full Test",syllabus:{Physics:["Full Syllabus as per NTA"],Chemistry:["Full Syllabus as per NTA"],Botany:["Full Syllabus as per NTA"],Zoology:["Full Syllabus as per NTA"]}},
    {number:19,title:"AITS-11",date:"2027-04-18",type:"Full Test",syllabus:{Physics:["Full Syllabus as per NTA"],Chemistry:["Full Syllabus as per NTA"],Botany:["Full Syllabus as per NTA"],Zoology:["Full Syllabus as per NTA"]}},
    {number:20,title:"AITS-12",date:"2027-04-21",type:"Full Test",syllabus:{Physics:["Full Syllabus as per NTA"],Chemistry:["Full Syllabus as per NTA"],Botany:["Full Syllabus as per NTA"],Zoology:["Full Syllabus as per NTA"]}},
    {number:21,title:"AITS-13",date:"2027-04-25",type:"Full Test",syllabus:{Physics:["Full Syllabus as per NTA"],Chemistry:["Full Syllabus as per NTA"],Botany:["Full Syllabus as per NTA"],Zoology:["Full Syllabus as per NTA"]}},
    {number:22,title:"AITS-14",date:"2027-04-28",type:"Full Test",syllabus:{Physics:["Full Syllabus as per NTA"],Chemistry:["Full Syllabus as per NTA"],Botany:["Full Syllabus as per NTA"],Zoology:["Full Syllabus as per NTA"]}}
  ]
};
