// Run with: node tests/reliability-contract.test.cjs
const fs = require('node:fs');
const assert = require('node:assert/strict');
const html = fs.readFileSync('index.html','utf8');
const api = fs.readFileSync('api/chat.js','utf8');
const sw = fs.readFileSync('sw.js','utf8');
assert.match(html, /function hasStudyContext\(\)/);
assert.match(html, /function removeLegacyGenericPlan\(\)/);
assert.match(html, /function mentorFetch\(payload\)/);
assert.match(html, /No plan yet\. Tell NEETOS about your coaching\/classes/);
assert.match(html, /generateDailyPlan\('after profile update'\)/);
assert.doesNotMatch(html, /function ensureRevisionQueue/);
assert.doesNotMatch(html, /id="revisionQueue"/);
assert.match(api, /gemini-3\.8-flash/);
assert.match(api, /gemini-3\.6-flash/);
assert.match(api, /gemini-3\.5-flash-lite/);
assert.match(api, /x-goog-api-key/);
assert.match(api, /AbortController/);
assert.match(api, /thinkingLevel:'medium'/);
assert.doesNotMatch(api, /temperature\s*:/);
assert.match(api, /normalizedHistory/);
assert.match(sw, /neetos-shell-v8/);
assert.match(sw, /test-planner\.js/);
assert.match(api, /test-planner\.js/);
assert.match(api, /Permanent imported test planner/);
assert.match(html, /test-planner\.js/);
assert.match(html, /subject-wise syllabus/);
const inlineScripts = [...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m => m[1]).filter(s => s.trim());
assert.equal(inlineScripts.length, 1);
for (const script of inlineScripts) new Function(script);
new Function(api.replace(/^import .*test-planner\.js';\s*/m, '').replace(/^export default async function handler/m, 'async function handler'));
console.log('NEETOS source-contract checks passed.');
